### ISSUE TITLE
'first' can't be used as a name attribute

### ISSUE THREAD

**Issue by stocksp** [garygreen/dominar#15]
If 'first' is used as the name attribute like:
`<input name="first" type="text" class="form-control"/>`
Dominar gets confused and we crash in line 815

```
validate.reject(this.validator.errors.first(name));
```

with 'first' as the name, errors becomes an array which doesn't have a first method.

Very easy to see in your demo..  Just change 'userName' to 'first'  and you get the error.

**Comment by garygreen** [comment]
Yeah, this is an issue with validatorjs as in https://github.com/skaterdav85/validatorjs/issues/56

Will be fixed when I release validator js 2.0
