### ISSUE TITLE
dist/ folder not up-to-date

### ISSUE THREAD

**Issue by vlascik** [garygreen/dominar#22]
Files in dist/ folder are not up-to-date, which will trip people up when trying to make Dominar work according to documentation (e.g. on async validations, dist files miss Dominar.Validator, constructor parameters are different, etc.)

**Comment by garygreen** [comment]
Yes sorry, I have been intending to release a new version. Will release new version tonight

**Comment by vlascik** [comment]
Thanks :)

**Comment by garygreen** [comment]
Will cut a release soon.
