### ISSUE TITLE
Remote requests fire even if previous validations in the chain fail

### ISSUE THREAD

**Issue by vlascik** [garygreen/dominar#23]
Remote requests fire even if previous validations in the chain fail, e.g. in
`rules: 'required|email|username_available'`
even if `email` fails,`username_available` fires a request to server anyway, which stresses the server needlessly.

**Comment by garygreen** [comment]
Yes that is a bit silly. Support needs to be added upstream in skaterdav85/validatorjs/issues/63

**Comment by vlascik** [comment]
ok, you're right, i'll close it here
