### ISSUE TITLE
Add validation events (validationFailed/Passed) to use with other triggers, not just submit

### ISSUE THREAD

**Issue by vlascik** [garygreen/dominar#25]
I think it would be helpful if dominar would also have something like dominarValidationPassed / dominarValidationFailed events even without submitting the form, so that users could e.g. disable action buttons if the validation didn't pass.
Or maybe this could be achieved in some other way?

**Comment by garygreen** [comment]
That would be pretty useful. Could add something along the lines of:

``` javascript
var form = document.getElementById('my-form');
var btn = document.getElementById('submit-btn');
form.addEventListener('dominarValidatedField', function(passed, field, dominar) {
    if (dominar.isPassing())
    {
        btn.removeAttribute('disabled');
    }
    else
    {
        btn.setAttribute('disabled', 'disabled');
    }
});
```

**Comment by vlascik** [comment]
Sounds good, would dominar.isPassing() mean all fields on a form passing? Would field also have isPassing()?

**Comment by garygreen** [comment]
Yes, dominar.isPassing() means are all fields passing and the actual result
of the field is `passes` as supplied in the closure. Or could add
`field.isPasing()` as well

**Comment by vlascik** [comment]
Ok, great, thanks.

**Comment by garygreen** [comment]
Closing this in favour of #26
